--  Generated by Aquarius/Options
package Agrippa.Options is

   function Randomise return Boolean;
   function Random_Seed return Natural;
   function Gnoga_UI return Boolean;
   function Text_UI return Boolean;

end Agrippa.Options;
